### ISSUE TITLE
Add me

### ISSUE THREAD

**Issue by midizzz** [unspentspace/melbourne#13]
**Documents related:** ALL OF THEM

**Change description:** minor adjustments

**Comment by unspentspace-admin** [comment]
A bit more context @midizzz ? Or is this a note to self.

**Comment by unspentspace-admin** [comment]
@midizzz @Cyberpunk-Hardware ?

**Comment by midizzz** [comment]
Whats that?

**Comment by unspentspace-admin** [comment]
Ok. I'll close this one then.
